### PR TITLE
[Monster slap] Add monster slap alias

### PR DESCRIPTION
**Pull request by un1versal**
This is an multiple array with multiple interchangeable entries that are mixed at $rand that aim to provide a slightly different slap result each time.

The careful syntax construction of each entry is what makes all the entries work in any possible combination while still making sense. This can easily be expanded or modified to suit each individual user at will.
The only limitation is that $rand value could be more random and less repetitive maybe that's something pragma or someone else can improve in core.

This is released into the public domain license (cant get more permissive than that) to stimulate the creative and hopefully team spirit while spanking your IRC victims with some really neat monster slaps and fuel the future of the classic IRC slap.

### CODE REVIEW

**Comment by un1versal** [comment]
Thoughts, wishes, hopes and dreams? anyone?! is this MIC on?

**Comment by ctrlaltca** [comment]
Typically scripts in this repo are packages as an installable addon, but i suppose this is not mandatory.

**Comment by un1versal** [comment]
And how does that differ from this alias, you still have to do something in kvirc no?

Looking at some install.kvs its exactly what this is. Unless Im missing something.

I suppose if you like I can make a addon package from this... let me know...

**Comment by pragmaware** [comment]
Making a very basic addon is quite easy. Just call

addon.register(...){ <uninstall_code> }

where <uninstall_code> should remove any trace of your addon from kvirc: in your case it would just remove the single alias.

**Pull request merged**
